# Generated by Django 2.2.4 on 2020-03-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='capital',
        ),
        migrations.AddField(
            model_name='expert',
            name='capitals',
            field=models.ManyToManyField(related_name='capitals', to='api.Capital'),
        ),
        migrations.AddField(
            model_name='project',
            name='capital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Capital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='project_categories', to='api.Category'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='categories',
            field=models.ManyToManyField(related_name='expert_categories', to='api.Category'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='categories',
            field=models.ManyToManyField(related_name='investor_categories', to='api.Category'),
        ),
    ]
