# Generated by Django 2.2.4 on 2020-03-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200308_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='cost',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
