# Generated by Django 2.2.6 on 2019-11-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис сегменту')),
                ('stream_amount', models.IntegerField(blank=True, null=True, verbose_name='Кількість потоків')),
                ('district_id', models.IntegerField(blank=True, null=True, verbose_name='ID району')),
                ('road_index', models.TextField(blank=True, null=True, verbose_name='Індекс дороги')),
                ('road_type_significance', models.TextField(blank=True, null=True, verbose_name='Значення дороги')),
                ('road_destination', models.TextField(blank=True, null=True, verbose_name='Сполучення')),
                ('geom_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.DictStreetGeomType')),
                ('topocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.DictStreetTopocode')),
                ('tract_mtz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.DictStreetTract')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.DictStreetType')),
            ],
            options={
                'db_table': 'dit_segment',
                'verbose_name': 'Сегмент',
                'verbose_name_plural': 'Перелік Сегментів',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SegmentStreet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата початку')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата кінця')),
                ('dit_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Segment')),
            ],
            options={
                'db_table': 'dit_segment_street',
                'verbose_name': "Зв'язок між вулицею та сегментом",
                'verbose_name_plural': "Зв'язки між вулицями та сегментами",
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва вулиці')),
                ('prev_id', models.IntegerField(blank=True, null=True, verbose_name='Попередній ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Опис вулиці')),
                ('significance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Значення')),
                ('geom_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.DictStreetGeomType')),
                ('segments', models.ManyToManyField(through='main.SegmentStreet', to='main.Segment')),
                ('topocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.DictStreetTopocode')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.DictStreetType')),
            ],
            options={
                'db_table': 'dit_street',
                'verbose_name': 'Вулиця',
                'verbose_name_plural': 'Перелік вулиць',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='segmentstreet',
            name='dit_street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Street'),
        ),
    ]
