# Generated by Django 2.2.6 on 2019-11-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0006_auto_20191111_1810'),
        ('main', '0002_auto_20191111_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='district_id',
        ),
        migrations.AddField(
            model_name='segment',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.DictDistricts'),
        ),
    ]
