# Generated by Django 2.2.6 on 2019-11-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191111_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segmentstreet',
            old_name='dit_segment',
            new_name='segment',
        ),
        migrations.RenameField(
            model_name='segmentstreet',
            old_name='dit_street',
            new_name='street',
        ),
    ]
