# Generated by Django 2.2.6 on 2019-11-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictStreetDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Тип документу')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис документу')),
            ],
            options={
                'db_table': 'dit_dict_street_documents',
                'verbose_name': 'Тип документу',
                'verbose_name_plural': 'Словник типів документів',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictStreetGeomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Тип геометрії')),
            ],
            options={
                'db_table': 'dit_dict_street_geom_type',
                'verbose_name': 'Тип геометрії',
                'verbose_name_plural': 'Словник типів геометрій',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictStreetTopocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Топокод')),
            ],
            options={
                'db_table': 'dit_dict_street_topocode',
                'verbose_name': 'Топокод',
                'verbose_name_plural': 'Словник топокодів',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictStreetTract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Тип тракту')),
            ],
            options={
                'db_table': 'dit_dict_street_tract',
                'verbose_name': 'Тип тракту',
                'verbose_name_plural': 'Словник типів тракту',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictStreetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип вулиці')),
            ],
            options={
                'db_table': 'dit_dict_street_type',
                'verbose_name': 'Тип Вулиці',
                'verbose_name_plural': 'Словник типів вулиць',
                'managed': True,
            },
        ),
    ]
