# Generated by Django 2.2.6 on 2019-11-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictDistricts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Назва району')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Словник районів',
                'db_table': 'dit_dict_districts',
                'managed': True,
            },
        ),
    ]
