# Generated by Django 2.2.6 on 2019-11-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictdistricts',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Словник районів'},
        ),
        migrations.AlterModelOptions(
            name='dictstreetdocuments',
            options={'verbose_name': 'Тип документу', 'verbose_name_plural': 'Словник типів документів'},
        ),
        migrations.AlterModelOptions(
            name='dictstreetgeomtype',
            options={'verbose_name': 'Тип геометрії', 'verbose_name_plural': 'Словник типів геометрій'},
        ),
        migrations.AlterModelOptions(
            name='dictstreettopocode',
            options={'verbose_name': 'Топокод', 'verbose_name_plural': 'Словник топокодів'},
        ),
        migrations.AlterModelOptions(
            name='dictstreettract',
            options={'verbose_name': 'Тип тракту', 'verbose_name_plural': 'Словник типів тракту'},
        ),
        migrations.AlterModelOptions(
            name='dictstreettype',
            options={'verbose_name': 'Тип Вулиці', 'verbose_name_plural': 'Словник типів вулиць'},
        ),
    ]
