# Generated by Django 2.2.6 on 2019-11-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_auto_20191111_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
