# Generated by Django 2.2.6 on 2019-11-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0005_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictdistricts',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва району'),
        ),
        migrations.AlterField(
            model_name='dictstreetdocuments',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Опис документу'),
        ),
        migrations.AlterField(
            model_name='dictstreetdocuments',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип документу'),
        ),
        migrations.AlterField(
            model_name='dictstreetgeomtype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип геометрії'),
        ),
        migrations.AlterField(
            model_name='dictstreettract',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип тракту'),
        ),
    ]
